[package]
name = "sky_ecs_derive"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Derive macros for Sky ECS typed queries"
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
