[package]
name = "sky_ecs_comparison"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
sky_ecs = { path = "../../crates/sky_ecs" }
criterion = "0.8.2"
cgmath = "0.18"
hecs = "0.10.5"
bevy_ecs = "0.18.1"
flecs_ecs = "0.2.2"
rand = "0.8"

[[bench]]
name = "fair"
path = "benches/fair.rs"
harness = false
